In [2]:
import pandas as pd
import tqdm

# AHV-IV MEMENTO

In [ ]:
df = pd.read_csv("indexing/data/to_upsert/ahv_iv_memento/ahv_iv_de_fr_it_tags_subtopics_llm_EMBED.csv")
df.rename(columns={"text_summary": "summary_embedding"}, inplace=True)
len(df)

In [ ]:
df.head()

In [ ]:
df.to_csv("indexing/data/to_upsert/ahv_iv_memento/ahv_iv_de_fr_it_tags_subtopics_llm_EMBED.csv", index=None)

# EAK - AHV LERNBAUSTEIN 2024

In [ ]:
df = pd.read_csv("indexing/data/to_upsert/AHV_Lernbaustein_2024/AHV_Lernbaustein_2024_tags_llm_EMBED.csv")
df.rename(columns={"text_summary": "summary_embedding"}, inplace=True)
len(df)

In [ ]:
df.head()

In [ ]:
df.to_csv("indexing/data/to_upsert/AHV_Lernbaustein_2024/AHV_Lernbaustein_2024_tags_llm_EMBED.csv", index=None)

# EAK PRAXISLEITFADEN 2024

In [ ]:
df = pd.read_csv("indexing/data/to_upsert/Guide_Pratique_CAF_CFC/guide_pratique_caf_cfc_de_tags_llm.csv")
len(df)

In [ ]:
df.head()

# AKIS

In [ ]:
df = pd.read_csv("indexing/data/zas_eak_copilot/akis/akis_EMBED_2.csv")
len(df)

In [ ]:
df.head()

# EAK ADMIN CH

In [ ]:
df = pd.read_csv("indexing/data/to_upsert/eak_admin_ch/eak_admin_ch_de_fr_tags_NEW.csv")
len(df)

In [ ]:
df.head()

# FEDLEX

In [ ]:
df = pd.read_csv("indexing/data/to_upsert/fedlex/lavs.csv")
len(df)

In [ ]:
df.head()

# OFAS

In [6]:
df = pd.read_csv("../preprocessing/output/ofas.csv")
len(df)

57

In [7]:
df.head()

,url,text,language,tags,subtopics,summary,doctype,organizations,hyq,hyq_declarative
0,https://sozialversicherungen.admin.ch/it/d/690...,"1 Panoramica delle direttive sui contributi, s...",it,[],[],NaN,context_doc,OFAS,NaN,NaN
1,https://sozialversicherungen.admin.ch/it/d/695...,Direttive sull’obbligo assicurativo nell’AVS/A...,it,[],[],NaN,context_doc,OFAS,NaN,NaN
2,https://sozialversicherungen.admin.ch/it/d/694...,Direttive sul salario determinante nell ’AVS/A...,it,[],[],NaN,context_doc,OFAS,NaN,NaN
3,https://sozialversicherungen.admin.ch/it/d/692...,Direttive sulla riscossione dei contributi nel...,it,[],[],NaN,context_doc,OFAS,NaN,NaN
4,https://sozialversicherungen.admin.ch/it/d/695...,Direttive sui contributi dei lavoratori indipe...,it,[],[],NaN,context_doc,OFAS,NaN,NaN

# AUTOCOMPLETE

In [ ]:
df = pd.read_csv("indexing/data/to_upsert/autocomplete/question.csv")

df["text_embedding"] = None

len(df)

In [ ]:
df.head()

In [ ]:
for i, row in tqdm.tqdm(df.iterrows()):

    embeddings = await get_embedding([row.text])

    df.loc[i, "text_embedding"] = str(embeddings[0].embedding)

In [ ]:
df.tail()

In [ ]:
df.to_csv("indexing/data/to_upsert/autocomplete/question_EMBED.csv", index=None)

In [ ]:
df.to_csv("indexing/data/to_upsert/autocomplete/eak_admin_ch_de_fr_tags_EMBED.csv", index=None)

# EMBEDDING

In [8]:
MAX_INPUT_TOKENS = 8191

In [9]:
import tiktoken
tokenizer = tiktoken.get_encoding("cl100k_base")

In [15]:
import sys
import os

# Add the src directory to the system path
sys.path.append(os.path.abspath(os.path.join('..', '..', 'src', 'copilot', 'app')))

# Now you can import the function
from utils.embedding import get_embedding

c:\Users\deyan\cdc\ZAS-EAK-CopilotGPT\venv\Lib\site-packages\pydantic\_internal\_config.py:341: UserWarning: Valid config keys have changed in V2:
* 'allow_population_by_field_name' has been renamed to 'populate_by_name'
* 'smart_union' has been removed
  warnings.warn(message, UserWarning)

In [16]:
df["text_embedding"] = None
df["tags_embedding"] = None
df["subtopics_embedding"] = None
df["summary_embedding"] = None
df["hyq_embedding"] = None
df["hyq_declarative_embedding"] = None

In [20]:
tags_embedding = await get_embedding(df.loc[0, "tags"]) # If tags are all the same

for i, row in tqdm.tqdm(df.iterrows()):

    try:
        tokens = tokenizer.encode(row.text)
        if len(tokens) > MAX_INPUT_TOKENS:
            truncated_text = tokenizer.decode(tokens[:MAX_INPUT_TOKENS])
            embeddings = await get_embedding(truncated_text)
        else:
            embeddings = await get_embedding(row.text)
    except Exception as e:
        embeddings = None

    df.loc[i, "text_embedding"] = str(embeddings) if embeddings else None
    #df.loc[i, "summary_embedding"] = str(embeddings[1].embedding)
    #df.loc[i, "hyq_embedding"] = str(embeddings[2].embedding)
    #df.loc[i, "hyq_declarative_embedding"] = str(embeddings[3].embedding)
    #df.loc[i, "subtopics_embedding"] = str(embeddings[4].embedding)
    df.loc[i, "tags_embedding"] = str(tags_embedding)

2025-03-03 16:25:41,391 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
2025-03-03 16:25:41,391 - utils.embedding - INFO - Embedding successfull with model: text-embedding-3-small
0it [00:00, ?it/s]2025-03-03 16:25:42,487 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
2025-03-03 16:25:42,489 - utils.embedding - INFO - Embedding successfull with model: text-embedding-3-small
1it [00:01,  1.10s/it]2025-03-03 16:25:43,024 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
2025-03-03 16:25:43,026 - utils.embedding - INFO - Embedding successfull with model: text-embedding-3-small
2it [00:01,  1.30it/s]2025-03-03 16:25:43,887 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
2025-03-03 16:25:43,888 - utils.embedding - INFO - Embedding successfull with model: text-embedding-3-small
3it [00:02,  1.23it/s]2025-03-03 16:25:44,698 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
2025-03-03 16:25:44,700 - utils.embedding - INFO - Embedding successfull with model: text-embedding-3-small
4it [00:03,  1.23it/s]2025-03-03 16:25:45,387 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
2025-03-03 16:25:45,389 - utils.embedding - INFO - Embedding successfull with model: text-embedding-3-small
5it [00:03,  1.30it/s]2025-03-03 16:25:46,099 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
2025-03-03 16:25:46,103 - utils.embedding - INFO - Embedding successfull with model: text-embedding-3-small
6it [00:04,  1.33it/s]2025-03-03 16:25:47,197 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
2025-03-03 16:25:47,198 - utils.embedding - INFO - Embedding successfull with model: text-embedding-3-small
7it [00:05,  1.16it/s]2025-03-03 16:25:47,934 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
2025-03-03 16:25:47,937 - utils.embedding - INFO - Embedding successfull with model: text-embedding-3-small
8it [00:06,  1.22it/s]2025-03-03 16:25:48,436 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
2025-03-03 16:25:48,438 - utils.embedding - INFO - Embedding successfull with model: text-embedding-3-small
9it [00:07,  1.38it/s]2025-03-03 16:25:48,877 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
2025-03-03 16:25:48,879 - utils.embedding - INFO - Embedding successfull with model: text-embedding-3-small
10it [00:07,  1.57it/s]2025-03-03 16:25:49,171 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
2025-03-03 16:25:49,173 - utils.embedding - INFO - Embedding successfull with model: text-embedding-3-small
11it [00:07,  1.88it/s]2025-03-03 16:25:49,844 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
2025-03-03 16:25:49,846 - utils.embedding - INFO - Embedding successfull with model: text-embedding-3-small
12it [00:08,  1.74it/s]2025-03-03 16:25:50,370 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
2025-03-03 16:25:50,371 - utils.embedding - INFO - Embedding successfull with model: text-embedding-3-small
13it [00:08,  1.79it/s]2025-03-03 16:25:51,439 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
2025-03-03 16:25:51,440 - utils.embedding - INFO - Embedding successfull with model: text-embedding-3-small
14it [00:10,  1.40it/s]2025-03-03 16:25:52,225 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
2025-03-03 16:25:52,226 - utils.embedding - INFO - Embedding successfull with model: text-embedding-3-small
15it [00:10,  1.36it/s]2025-03-03 16:25:52,744 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
2025-03-03 16:25:52,746 - utils.embedding - INFO - Embedding successfull with model: text-embedding-3-small
16it [00:11,  1.49it/s]2025-03-03 16:25:53,578 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
2025-03-03 16:25:53,580 - utils.embedding - INFO - Embedding successfull with model: text-embedding-3-small
17it [00:12,  1.39it/s]2025-03-03 16:25:54,114 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
2025-03-03 16:25:54,118 - utils.embedding - INFO - Embedding successfull with model: text-embedding-3-small
18it [00:12,  1.50it/s]2025-03-03 16:25:54,567 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
2025-03-03 16:25:54,569 - utils.embedding - INFO - Embedding successfull with model: text-embedding-3-small
19it [00:13,  1.66it/s]2025-03-03 16:25:55,439 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
2025-03-03 16:25:55,440 - utils.embedding - INFO - Embedding successfull with model: text-embedding-3-small
20it [00:14,  1.47it/s]2025-03-03 16:25:55,949 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
2025-03-03 16:25:55,951 - utils.embedding - INFO - Embedding successfull with model: text-embedding-3-small
21it [00:14,  1.59it/s]2025-03-03 16:25:56,393 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
2025-03-03 16:25:56,395 - utils.embedding - INFO - Embedding successfull with model: text-embedding-3-small
22it [00:15,  1.74it/s]2025-03-03 16:25:57,197 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
2025-03-03 16:25:57,198 - utils.embedding - INFO - Embedding successfull with model: text-embedding-3-small
23it [00:15,  1.55it/s]2025-03-03 16:25:57,661 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
2025-03-03 16:25:57,663 - utils.embedding - INFO - Embedding successfull with model: text-embedding-3-small
24it [00:16,  1.70it/s]2025-03-03 16:25:58,481 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
2025-03-03 16:25:58,482 - utils.embedding - INFO - Embedding successfull with model: text-embedding-3-small
25it [00:17,  1.52it/s]2025-03-03 16:25:58,965 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
2025-03-03 16:25:58,966 - utils.embedding - INFO - Embedding successfull with model: text-embedding-3-small
26it [00:17,  1.65it/s]2025-03-03 16:25:59,627 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
2025-03-03 16:25:59,629 - utils.embedding - INFO - Embedding successfull with model: text-embedding-3-small
27it [00:18,  1.61it/s]2025-03-03 16:26:00,079 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
2025-03-03 16:26:00,080 - utils.embedding - INFO - Embedding successfull with model: text-embedding-3-small
28it [00:18,  1.75it/s]2025-03-03 16:26:00,440 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
2025-03-03 16:26:00,441 - utils.embedding - INFO - Embedding successfull with model: text-embedding-3-small
29it [00:19,  1.97it/s]2025-03-03 16:26:00,876 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
2025-03-03 16:26:00,944 - utils.embedding - INFO - Embedding successfull with model: text-embedding-3-small
30it [00:19,  1.97it/s]2025-03-03 16:26:01,518 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
2025-03-03 16:26:01,520 - utils.embedding - INFO - Embedding successfull with model: text-embedding-3-small
31it [00:20,  1.90it/s]2025-03-03 16:26:03,363 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
2025-03-03 16:26:03,366 - utils.embedding - INFO - Embedding successfull with model: text-embedding-3-small
32it [00:21,  1.08it/s]2025-03-03 16:26:03,758 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
2025-03-03 16:26:03,760 - utils.embedding - INFO - Embedding successfull with model: text-embedding-3-small
33it [00:22,  1.31it/s]2025-03-03 16:26:04,194 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
2025-03-03 16:26:04,195 - utils.embedding - INFO - Embedding successfull with model: text-embedding-3-small
34it [00:22,  1.50it/s]2025-03-03 16:26:04,718 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
2025-03-03 16:26:04,720 - utils.embedding - INFO - Embedding successfull with model: text-embedding-3-small
35it [00:23,  1.60it/s]2025-03-03 16:26:05,110 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
2025-03-03 16:26:05,115 - utils.embedding - INFO - Embedding successfull with model: text-embedding-3-small
36it [00:23,  1.80it/s]2025-03-03 16:26:05,515 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
2025-03-03 16:26:05,517 - utils.embedding - INFO - Embedding successfull with model: text-embedding-3-small
37it [00:24,  1.96it/s]2025-03-03 16:26:06,005 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
2025-03-03 16:26:06,007 - utils.embedding - INFO - Embedding successfull with model: text-embedding-3-small
38it [00:24,  1.99it/s]2025-03-03 16:26:06,446 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
2025-03-03 16:26:06,448 - utils.embedding - INFO - Embedding successfull with model: text-embedding-3-small
39it [00:25,  2.06it/s]2025-03-03 16:26:06,903 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
2025-03-03 16:26:06,905 - utils.embedding - INFO - Embedding successfull with model: text-embedding-3-small
40it [00:25,  2.10it/s]2025-03-03 16:26:07,340 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
2025-03-03 16:26:07,341 - utils.embedding - INFO - Embedding successfull with model: text-embedding-3-small
41it [00:25,  2.16it/s]2025-03-03 16:26:08,218 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
2025-03-03 16:26:08,219 - utils.embedding - INFO - Embedding successfull with model: text-embedding-3-small
42it [00:26,  1.70it/s]2025-03-03 16:26:08,666 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
2025-03-03 16:26:08,668 - utils.embedding - INFO - Embedding successfull with model: text-embedding-3-small
43it [00:27,  1.83it/s]2025-03-03 16:26:09,214 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
2025-03-03 16:26:09,216 - utils.embedding - INFO - Embedding successfull with model: text-embedding-3-small
44it [00:27,  1.83it/s]2025-03-03 16:26:10,303 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
2025-03-03 16:26:10,305 - utils.embedding - INFO - Embedding successfull with model: text-embedding-3-small
45it [00:28,  1.41it/s]2025-03-03 16:26:10,823 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
2025-03-03 16:26:10,825 - utils.embedding - INFO - Embedding successfull with model: text-embedding-3-small
46it [00:29,  1.53it/s]2025-03-03 16:26:11,387 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
2025-03-03 16:26:11,388 - utils.embedding - INFO - Embedding successfull with model: text-embedding-3-small
47it [00:29,  1.60it/s]2025-03-03 16:26:12,014 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
2025-03-03 16:26:12,016 - utils.embedding - INFO - Embedding successfull with model: text-embedding-3-small
48it [00:30,  1.60it/s]2025-03-03 16:26:12,506 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
2025-03-03 16:26:12,508 - utils.embedding - INFO - Embedding successfull with model: text-embedding-3-small
49it [00:31,  1.71it/s]2025-03-03 16:26:13,220 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
2025-03-03 16:26:13,222 - utils.embedding - INFO - Embedding successfull with model: text-embedding-3-small
50it [00:31,  1.60it/s]2025-03-03 16:26:13,688 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
2025-03-03 16:26:13,689 - utils.embedding - INFO - Embedding successfull with model: text-embedding-3-small
51it [00:32,  1.73it/s]2025-03-03 16:26:14,213 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
2025-03-03 16:26:14,215 - utils.embedding - INFO - Embedding successfull with model: text-embedding-3-small
52it [00:32,  1.78it/s]2025-03-03 16:26:14,631 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
2025-03-03 16:26:14,632 - utils.embedding - INFO - Embedding successfull with model: text-embedding-3-small
53it [00:33,  1.93it/s]2025-03-03 16:26:15,118 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
2025-03-03 16:26:15,122 - utils.embedding - INFO - Embedding successfull with model: text-embedding-3-small
54it [00:33,  1.96it/s]2025-03-03 16:26:15,758 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
2025-03-03 16:26:15,761 - utils.embedding - INFO - Embedding successfull with model: text-embedding-3-small
55it [00:34,  1.82it/s]2025-03-03 16:26:16,397 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
2025-03-03 16:26:16,399 - utils.embedding - INFO - Embedding successfull with model: text-embedding-3-small
56it [00:35,  1.74it/s]2025-03-03 16:26:16,718 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
2025-03-03 16:26:16,719 - utils.embedding - INFO - Embedding successfull with model: text-embedding-3-small
57it [00:35,  1.61it/s]

In [21]:
df.tail()

,url,text,language,tags,subtopics,summary,doctype,organizations,hyq,hyq_declarative,text_embedding,tags_embedding,subtopics_embedding,summary_embedding,hyq_embedding,hyq_declarative_embedding
52,https://sozialversicherungen.admin.ch/de/d/640...,Kreisschreiben über das Verfahren zur Leis- tu...,de,[],[],NaN,context_doc,OFAS,NaN,NaN,"[-0.004064788576215506, 0.036861587315797806, ...","[0.013414580374956131, 0.030635777860879898, 0...",None,None,None,None
53,https://sozialversicherungen.admin.ch/de/d/155...,EDI BSV | Kreisschreiben zum Übergangsrecht de...,de,[],[],NaN,context_doc,OFAS,NaN,NaN,"[0.010609467513859272, 0.04923446848988533, 0....","[0.013414580374956131, 0.030635777860879898, 0...",None,None,None,None
54,https://sozialversicherungen.admin.ch/de/d/629...,Erläuterungen zum Kreisschreiben über die Leis...,de,[],[],NaN,context_doc,OFAS,NaN,NaN,"[-0.04111221060156822, 0.04086235910654068, 0....","[0.013414580374956131, 0.030635777860879898, 0...",None,None,None,None
55,https://sozialversicherungen.admin.ch/de/d/693...,EDI BSV | Nachtrag 14 zur Wegleitung über die ...,de,[],[],NaN,context_doc,OFAS,NaN,NaN,"[-0.016585489735007286, 0.0013660902623087168,...","[0.013414580374956131, 0.030635777860879898, 0...",None,None,None,None
56,https://sozialversicherungen.admin.ch/de/d/184...,Nachtrag 4 zum Kreisschreiben über das Verfahr...,de,[],[],NaN,context_doc,OFAS,NaN,NaN,"[-0.0021825614385306835, 0.024891218170523643,...","[0.013414580374956131, 0.030635777860879898, 0...",None,None,None,None

In [ ]:
df.head()

In [ ]:
df.to_csv("indexing/data/zas_eak_copilot/akis/akis_EMBED_2.csv", index=None)

In [ ]:
df = pd.read_csv("indexing/data/zas_eak_copilot/akis/akis_EMBED_2.csv")

In [ ]:
df.tail()